### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by mastercoms** [deathcap/GlowstonePlusPlus#4]
Is there a checklist of things that is needed to be done?

I would love to help on this project.

**Comment by deathcap** [comment]
Hey thanks for your interest! Some tasks off the top of my head:

* Help test plugin compatibility, from http://www.spigotmc.org/resources/ and/or http://dev.bukkit.org/bukkit-plugins/ - especially interested in plugins that have updated for Spigot 1.8.3, possibly with new 1.8 features. If a plugin works or doesn't work on Glowstone++, would be also good to know whether it works or not on Glowstone, as well as earlier builds of Glowstone++. Features of interest (more in the commit log): banners, item frame rotation, bone meal, block targeting, deprecated methods, enchantments, rabbits

* General gameplay testing - haven't done much of this since I don't run a server, but any general bugs or feature requests from ordinary player usage could be helpful. Some of the changes from Glowstone may or may not have been destabilizing

* Merging and updating PRs from https://github.com/GlowstoneMC/Glowstone/pulls for Spigot's Bukkit API updates and other Glowstone++ changes to https://github.com/deathcap/GlowstonePlusPlus/pulls - I merged several, mostly those tagged "ready to pull", others require more testing or integration work or API porting. There are also pulls for the API in Glowkit https://github.com/GlowstoneMC/Glowkit/pulls but many are superseded by Spigot's Bukkit update, so I'd only want to take them if they add new API not already covered by Spigot

* Implementing the method stubs added to compile against Spigot-Bukkit - these are usually tagged with `//To change body of implemented methods use File | Settings | File Templates.` (though I should probably change that to `throw new UnsupportedOperationException`), and they are just placeholders, should be filled in at some point

* New features and fixes - there's a lot of functionality missing in Glowstone that is not in Glowstone++ either, any pull requests welcome (since this project is very experimental, I plan to be fairly liberal in accepting changes - I like this philosophy of "open open source" https://github.com/maxogden/voxel-engine/blob/master/contributing.md where the project is treated sort of like an "open wiki")

**Comment by mastercoms** [comment]
Is there a log of PRs you have merged?

**Comment by deathcap** [comment]
Yeah I put the PR information in the merge commits on https://github.com/deathcap/GlowstonePlusPlus/commits/master

```
git fetch upstream pull/<pr-num>/head:foo
git merge foo
git commit -a
Merge branch 'foo' <pr-title>
<pr-url>

Conflicts: ...
```

**Comment by mastercoms** [comment]
Ok I will start helping tomorrow. Thank you for starting this!
